print("----------------------")
print("Student Information")
print("----------------------")
name = input("Name :")
Age = input("Age :")
college = input("College :")
Branch = input("Branch :")
City = input("City: ")
